### ISSUE TITLE
ali-mobile dataset download problem

### ISSUE THREAD

**Issue by leungyukshing** [beta-team/beta-recsys#107]
after running download(), it ran wrong and give no tips for users.
Expect: this dataset should be download manually and more tips should be given

![image](https://user-images.githubusercontent.com/29545063/81398630-2c089480-915c-11ea-8688-89fe1f7953ec.png)

**Comment by Alva112358** [comment]
![image](https://user-images.githubusercontent.com/26009009/81639553-d4fe0a80-944e-11ea-95be-79475bf3f30d.png)

I have added tips to ali_mobile dataset!
