### ISSUE TITLE
taobao dataset download problem

### ISSUE THREAD

**Issue by leungyukshing** [beta-team/beta-recsys#108]
after running the cmd download(), something went wrong.
Expect: more tips for users

![image](https://user-images.githubusercontent.com/29545063/81398665-42165500-915c-11ea-9aca-f4ee0ad6364f.png)

**Comment by Alva112358** [comment]
![image](https://user-images.githubusercontent.com/26009009/81638486-f4dfff00-944b-11ea-92bc-7e5806494fc3.png)

I have added tips to taobao dataset.
