### ISSUE TITLE
bug of yoochoose or similar datasets' random split process

### ISSUE THREAD

**Issue by Alva112358** [beta-team/beta-recsys#123]
When I run 'random_split' of yoochoose dataset, it throw the following bug.
![image](https://user-images.githubusercontent.com/26009009/81650282-3aa8c180-9464-11ea-9006-eb32fa20ba5f.png)

The statistics of this dataset is:
![image](https://user-images.githubusercontent.com/26009009/81650394-688e0600-9464-11ea-8e06-5bc831f10cd0.png)

count = 104
vocab_size = 37

**Comment by leungyukshing** [comment]
@mengzaiqiao this error happens because after filtering, we expect to neg sample 104 times (no repeat), but the dataset just has 37 different items.

**Comment by mengzaiqiao** [comment]
This the item number of this dataset is particularly small, I am gonna use a threshold to specify the minmum number of item (e.g. 1000) that need to use the negative sampling.
