### ISSUE TITLE
create a docker image for the framework

### ISSUE THREAD

**Issue by mengzaiqiao** [beta-team/beta-recsys#254]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leungyukshing** [comment]
Work Progress:

- [ ] Sign for Docker Hub.
- [ ] Create a Dockerfile for build.
- [ ] Push a stable version to Docker Hub.
- [ ] Add mirrors for download when building images.
