### ISSUE TITLE
Add amazon datasets

### ISSUE THREAD

**Issue by mengzaiqiao** [beta-team/beta-recsys#259]
Incorporate Amazon Review Datasets.

website: http://jmcauley.ucsd.edu/data/amazon/links.html

Working Progress:

@leungyukshing 
- [x] Amazon Instant Video
- [x] Musical Instruments
- [x] Digital Music
- [x] Baby
- [x] Patio, Lawn and Garden
- [x] Grocery and Gourmet Food
- [x] Automotive
- [x] Pet Supplies

@Alva112358 
- [x] Office Products
- [x] Apps for Android
- [x] Beauty
- [x] Tools and Home Improvement
- [x] Video Games
- [x] Toys and Games
- [x] Health and Personal Care
- [x] Cell Phones and Accessories

@ChaosCodes 
- [x] Sports and Outdoors
- [x] Kindle Store
- [x] Home and Kitchen
- [x] Clothing, Shoes and Jewelry
- [x] CDs and Vinyl
- [x] Movies and TV
- [x] Electronics
- [x] Books

**Comment by leungyukshing** [comment]
@leungyukshing 
- [ ] Amazon Instant Video
- [ ] Musical Instruments
- [ ] Digital Music
- [ ] Baby
- [ ] Patio, Lawn and Garden
- [ ] Grocery and Gourmet Food
- [ ] Automotive
- [ ] Pet Supplies

@Alva112358 
- [ ] Office Products
- [ ] Apps for Android
- [ ] Beauty
- [ ] Tools and Home Improvement
- [ ] Video Games
- [ ] Toys and Games
- [ ] Health and Personal Care
- [ ] Cell Phones and Accessories

@ChaosCodes 
- [ ] Sports and Outdoors
- [ ] Kindle Store
- [ ] Home and Kitchen
- [ ] Clothing, Shoes and Jewelry
- [ ] CDs and Vinyl
- [ ] Movies and TV
- [ ] Electronics
- [ ] Books
