### ISSUE TITLE
string-to-int encoder

### ISSUE THREAD

**Issue by leungyukshing** [beta-team/beta-recsys#260]
For some dataset, they use string value as their user_id, item_id. But in our data model, we require these field should be int or float, so we need an algorithm to encode string to int.

**Comment by leungyukshing** [comment]
After discussion with @ChaosCodes and @Alva112358 , out of simplicity, we would like to do a string-to-int mapping in preprocess. That is, we will map each string onto a unique number.

**Comment by mengzaiqiao** [comment]
Are there any difficulties if we directly process the DatFrame with a string user/item column? If we do a string-to-int mapping, should we save such mapping dict so that the users can retrieval the real user/item id using that dict?

**Comment by leungyukshing** [comment]
Actually if we use mapping, it will be difficult for users to retrieve the real id. But for the first question, it seems that we can directly process string type.

**Comment by mengzaiqiao** [comment]
Before we put these train/validate/test data into the model, we will conduct a [reindex](https://github.com/beta-team/beta-recsys/blob/master/beta_rec/data/base_data.py#L59) operation to make sure the all the id be an int/long type. So I would suggest that we still keep the string until we put them into the base_data class.

**Comment by leungyukshing** [comment]
Got it!
