### ISSUE TITLE
figures in the documentation page cannot be shown normally

### ISSUE THREAD

**Issue by mengzaiqiao** [beta-team/beta-recsys#289]
https://beta-recsys.readthedocs.io/en/latest/contribute/standardization-of-code-format-and-documentation.html#

**Comment by leungyukshing** [comment]
@mengzaiqiao  After investigation, this is due to the change of path in community repo. Because we use the address in github, and the relative path in community repo has been changed, so the previous URL is invalid now. I'll update all the path in two days.

**Comment by leungyukshing** [comment]
@mengzaiqiao Already fixed! After merging into master, the documentation will automatically re-build!
