### ISSUE TITLE
The complexity of leave-one-out can be improved in O(n)

### ISSUE THREAD

**Issue by mengzaiqiao** [beta-team/beta-recsys#351]
**Is your feature request related to a problem? Please describe.**
``` python
def leave_one_out(actions):
user_actions = defaultdict(list)
for action in sorted(actions, key = lambda action: action.timestamp):
user_actions[action.user_id].append(action)

train_actions = []
test_actions = []
val_actions = []

for user in user_actions:
if len(user_actions[user]) < 3:
train_actions += user_actions[user]
else:
train_actions += user_actions[user][:-2]
action_val, action_test = user_actions[user][-2:]
if random.randint(0, 1) == 0:
action_val, action_test = action_test, action_val
val_actions.append(action_val)
test_actions.append(action_test)
return train_actions, test_actions, val_actions
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leungyukshing** [comment]
I've try to implement an improved version according to the above code, but I can't see any improvements. However I come up with an idea that may work.

Basically there are two stages in this function. First we construct a map to record each user and its records. Second we do `leave_one_out` for each user by manipulating its records.

How about parallel the second stage? Multi-thread is not working in Python but we can use Multi-process.

**Comment by leungyukshing** [comment]
I've implemented an experimental version and test on Movielens_1m. There is indeed some improvements on time cost.

Origin Version: About 170s
Parallel Version: About 105s

Undoubtedly, parallel version provides scalability and may achievement better improvements on larger datasets.

**Comment by mengzaiqiao** [comment]
I have rewritten the leave-one-out method using the following codes:
```python
def leave_one_out(data):
    data[DEFAULT_FLAG_COL] = "train"
    data.sort_values(by=[DEFAULT_TIMESTAMP_COL], ascending=False, inplace=True)
    data.loc[data.groupby([DEFAULT_USER_COL]).head(2).index,DEFAULT_FLAG_COL]="validate"
    data.loc[data.groupby([DEFAULT_USER_COL]).head(1).index,DEFAULT_FLAG_COL]="test"
```
which gives an O(n) complexity.

This split method can be done in 2 seconds, 
![](https://tva1.sinaimg.cn/large/0081Kckwgy1gljijzs5i6j30lh05et9l.jpg)

and in 30 seconds when it is with a negative sampling test set.

![](https://tva1.sinaimg.cn/large/0081Kckwgy1gljip9mhkoj30q104ewfn.jpg)
