### ISSUE TITLE
dependency check

### ISSUE THREAD

**Issue by leungyukshing** [beta-team/beta-recsys#360]
check the compatibility of dependencies and sync to conda

**Comment by mengzaiqiao** [comment]
-  [ ] Check the compatibility of the latest python version.
-  [ ] Check the compatibility of the latest PyTorch version.
-  [ ] Check the compatibility of the latest CI dependent packages, e.g. isort, flake8, black, flake8_nb
-  [ ] Check other packages' dependencies.
